require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'reactApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  # Pods for reactApp
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

 # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    ################### ADD THE FOLLOWING #########################
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
      if target.name == "React-Core.common-AccessibilityResources"
        target.remove_from_project
      end
      if target.name == "React-Core-AccessibilityResources"
        target.remove_from_project
      end
    end
    ###############################################################
  end

  target 'reactAppTests' do
    inherit! :complete
    # Pods for testing
  end


  # target 'reactAppUITests' do
  #     # Pods for testing
  #   end
  #   # Enables Flipper.
  #   #
  #   # Note that if you have use_frameworks! enabled, Flipper will not work and
  #   # you should disable these next few lines.
  #   use_flipper!
  #   post_install do |installer|
  #     flipper_post_install(installer)
  #   end
end
